### ISSUE TITLE
test.rb:2:in `<main>': uninitialized constant Mumble (NameError)

### ISSUE THREAD

**Issue by aphex3k** [mattvperry/mumble-ruby#55]
If I execute the example from the Basic Usage I receive the following error:

`kfm.rb:2:in `<main>': uninitialized constant Mumble (NameError)`

The installation seemed to go ok.

**Comment by XxTheMatrix101xX** [comment]
i have the same issue. im trying to build a bot but have no experience with ruby so i have no clue how to fix this....

**Comment by dafoxia** [comment]
is `require 'mumble-ruby'` in your code?
