### ISSUE TITLE
Is there a way to stream from stdin?

### ISSUE THREAD

**Issue by belopols** [mattvperry/mumble-ruby#62]
Hi! Found your lib and everything works great.
Unfortunately, I'm not very familiar with Ruby, and I'm struggling with making the script pipe audio directly from stdin.
I've tried the following:
```ruby
    def stream_stdin()
      unless playing?
        ARGF.binmode
        @file = ARGF
        spawn_threads :produce, :consume
        @playing = true
      end
    end
```
But it responds with a cryptic error "SSL is shutdown" and dies.
```ruby
#<Thread:0x00c49f80@/var/lib/gems/2.5.0/gems/mumble-ruby-1.1.3/lib/mumble-ruby/thread_tools.rb:8 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	13: from /var/lib/gems/2.5.0/gems/mumble-ruby-1.1.3/lib/mumble-ruby/thread_tools.rb:8:in `block in spawn_thread'
	12: from /var/lib/gems/2.5.0/gems/mumble-ruby-1.1.3/lib/mumble-ruby/thread_tools.rb:8:in `loop'
	11: from /var/lib/gems/2.5.0/gems/mumble-ruby-1.1.3/lib/mumble-ruby/thread_tools.rb:8:in `block (2 levels) in spawn_thread'
	10: from /var/lib/gems/2.5.0/gems/mumble-ruby-1.1.3/lib/mumble-ruby/audio_player.rb:106:in `consume'
	 9: from /var/lib/gems/2.5.0/gems/mumble-ruby-1.1.3/lib/mumble-ruby/connection.rb:43:in `send_udp_packet'
	 8: from /var/lib/gems/2.5.0/gems/mumble-ruby-1.1.3/lib/mumble-ruby/connection.rb:57:in `send_data'
	 7: from /var/lib/gems/2.5.0/gems/mumble-ruby-1.1.3/lib/mumble-ruby/connection.rb:57:in `synchronize'
	 6: from /var/lib/gems/2.5.0/gems/mumble-ruby-1.1.3/lib/mumble-ruby/connection.rb:58:in `block in send_data'
	 5: from /usr/lib/ruby/2.5.0/openssl/buffering.rb:343:in `write'
	 4: from /usr/lib/ruby/2.5.0/openssl/buffering.rb:343:in `inject'
	 3: from /usr/lib/ruby/2.5.0/openssl/buffering.rb:343:in `each'
	 2: from /usr/lib/ruby/2.5.0/openssl/buffering.rb:344:in `block in write'
	 1: from /usr/lib/ruby/2.5.0/openssl/buffering.rb:325:in `do_write'
/usr/lib/ruby/2.5.0/openssl/buffering.rb:325:in `syswrite': SSL_write: protocol is shutdown (OpenSSL::SSL::SSLError)
```
When I pipe the same data from named pipe - everything works like a charm though, so the input is not an issue.
Thank you in advance!

**Comment by belopols** [comment]
Okay, the problem was simply with the fact that
```ruby
File.open()
```
is blocking
While ARGF is not. Putting ARGF in the loop resolved the issue and now everything works properly:
```ruby
ARGF.binmode
...
encode_sample ARGF.read(@encoder.frame_size * 2)
```
